# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeremy & Kate's Rooftop Wedding Extravaganza
description: Saturday, September 8th at 5:00 PM
version: 0.0.01
logo: site-logo.png # place in /img
social-image: og-image.jpg # place in /img
url: "https://www.jerandkate.club"
# analytics-code: UA-XXXXX-Y
maps-api: AIzaSyCBeEP6r1F0ottP3fIPo7fig92gfmBRCC4

# Favicon settings - use realfavicon generator
icon-color: '#5bbad5'
msapplication-TileColor: '#ffffff'
theme-color: '#ffffff'

# Build settings
permalink: pretty
destination: public
source: src
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  style: compressed # possible values: nested expanded compact compressed

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Exclude from processing.
#
# Don't forget that Jekyll automatically
# excludes files with a dot prefix
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - readme.md
  - jekyll-ignored/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - _redirects # for netlify

# keep_files: []
